### ISSUE TITLE
possibility of cloning only specific shapes with clone wizard

### ISSUE THREAD

**Issue by AdrianoWanderlingh** [formicidae-tracker/studio#102]
The current clone wizard allows to clone the entire ant shape without letting the user choose to clone only specific shape types (e.g. antennae), which would be very useful when re-designing only one shape type.

**Comment by atuleu** [comment]
Will be quite complex to do in the current state...

Maybe try to implement it in R. You can do such a thing with the API.

**Comment by atuleu** [comment]
This should be done programnatically by the user using the C++ or R API
