### ISSUE TITLE
Pose estimation navigation

### ISSUE THREAD

**Issue by tomrichardson** [formicidae-tracker/studio#104]
the up/down arrow keys allow the user to cycle through different thumbnails of a given individual, but the actual image is not updated unless the user double-clicks on the individual he/she/xe wants to view..

**Comment by atuleu** [comment]
So the actual shortcut is shift+up/down (navigate within the same tag
value) and ctrl+ up/down( navigate to next tag , first close up).

>
Up down arrow just navigate through the list and require enter or mouse
click to display the item.

Do the actual shortcut do not work on your computer ? If yes this is an
issue with your window manager not delivering those at fort-studio, as on a
stock gnome shell these shortcut are fine.

**Comment by tomrichardson** [comment]
Perfect, thanks.
Yes the shortcuts work on my computer.
