### ISSUE TITLE
Question: is the association between tag number and ant number repeatable or does it depend on the order in which the ants are created?

### ISSUE THREAD

**Issue by nathaliestroeymeyt** [formicidae-tracker/studio#109]
If two different people orient the same dataset independenty and create ants in a different order from one another, would the ant IDs be different between the two? This could happen e.g. for quality control purposes where the supervisor does it independently of a student to check reliability of data.
For general purposes it would be good to have a fixed convention so things can be comparable between users (perhaps it is already the case...?)

**Comment by atuleu** [comment]
Unfortunately the AntID, for various beyond the hook definition  must be as sequential as possible. Therefore myrmidon makes it very hard to build a set of Ant with a non sequential ID (it is possible, but in most use case, the programmer actively tried to reach this goal). 

For example let say you have in your experiment 6 ant with ID 1,2,4,5,6. If you cretae a new Ant, its ID will be 3, and the next one 7.

There are no possibility from the GUI to specify a rule to assign ID. but #111 show an example on how it could be done from R.
