### ISSUE TITLE
Question: how to keep track of which tags have already been used to create an ant and which tags have not?

### ISSUE THREAD

**Issue by nathaliestroeymeyt** [formicidae-tracker/studio#110]
When there are many ants, it would be possible through human error to 'miss' an ant when creating the IDs. Is there any way to keep track of tags that have not been assigned to an ant yet - and perhaps an option to discard irrelevant ones from that remaining list (e.g. tag that wereon the floor from the start)?

**Comment by atuleu** [comment]
Will be addressed in #124
