### ISSUE TITLE
Makes clearer in the UI the edition of Identification

### ISSUE THREAD

**Issue by nathaliestroeymeyt** [formicidae-tracker/studio#112]
VurtualMachine running Linux Mint 19 (off Ubuntu 18.04). The following options are not editable for me:

- on the Identification panel, the 'Use Global Tag Size' box is greyed out and not untickable so I could not edit the size for the queen. The default did not seem to work either as although I had entered the tag size in the first screen, this was displayed as "0.00mm" on this window

- on the Identification panel, the Start Time and End Time boxes were also greyed out and non-editable

**Comment by atuleu** [comment]
maybe make clearer that and iDentification needs to be selected
