### ISSUE TITLE
Avoids jump in shape in capsule editor when bringing centers really close to each other

### ISSUE THREAD

**Issue by nathaliestroeymeyt** [formicidae-tracker/studio#113]
- Is there a way to keep track of which ants have been already shaped, and on which picture? I added shaped to one ant, navigated away, and then could not find it again...Perhaps adding a column "shapes added" with a value of 0 or 1 or something like that? 

- The minimum length of the shape was a bit too long for small ants - I wanted to make it shorter but could not, when I brought the two central squares too close together the shape "switched sideways" to a very elongated shape

- what will happen with shape overlaps in the detection of interaction? It is not possible to have an exact partition of the ant body, so there are small portions of the ant body that would be attributed to two body parts simultaneously...would that result in duplicated interactions?

- the shapes are really good, but also a bit fiddly to manipulate at first - though I'm sure it's a matter of habit. Any way that a shape we are happy with can be moved (translated) / rotated without touching the relative configuration of the four squares?

**Comment by atuleu** [comment]
The minimum length of the shape was a bit too long for small ants - I wanted to make it shorter but could not, when I brought the two central squares too close together the shape "switched sideways" to a very elongated shape

**Comment by atuleu** [comment]
> * Is there a way to keep track of which ants have been already shaped, and on which picture? I added shaped to one ant, navigated away, and then could not find it again...Perhaps adding a column "shapes added" with a value of 0 or 1 or something like that?
Linked to #119 
> * The minimum length of the shape was a bit too long for small ants - I wanted to make it shorter but could not, when I brought the two central squares too close together the shape "switched sideways" to a very elongated shape
> * what will happen with shape overlaps in the detection of interaction? It is not possible to have an exact partition of the ant body, so there are small portions of the ant body that would be attributed to two body parts simultaneously...would that result in duplicated interactions?
Only interaction with different ant are reported, self-collisioned are pruned away
> * the shapes are really good, but also a bit fiddly to manipulate at first - though I'm sure it's a matter of habit. Any way that a shape we are happy with can be moved (translated) / rotated without touching the relative configuration of the four squares?
RTrasnlation is allowed, rotation not (yet??)

**Comment by atuleu** [comment]
Works on mint tina on Xorg.
