### ISSUE TITLE
Makes Timed Change data column names clearer

### ISSUE THREAD

**Issue by nathaliestroeymeyt** [formicidae-tracker/studio#116]
- I was not clear to me what the 'Timed changes' section does, as only a single time value is shown. What does this mean? The value in the main column (at the top) is valid until that time, then the value entered in the Timed Changes section is valid after that time? That may be confusing for people and as it is important, perhaps time ranges could be more explicit rather than a single time stamp...? 

- also, can more than one changes be implemented?

**Comment by atuleu** [comment]
Column should be 'From Date' and 'Value Becomes'
