### ISSUE TITLE
Scroller is not following time consistently

### ISSUE THREAD

**Issue by nathaliestroeymeyt** [formicidae-tracker/studio#117]
- Scroller was excrutiatingly slow on my system, making it impossible to fast scroll through the video. I know a lot of this is due to system limitations, but we talked about downsampling the frame rate when playing the video at high speed - could this also be implemented for the scroll? Is there any way to make it smoother? t is such an important function just to see what the ants are doing and having complete control of what we are looking at that I feel it is important to revisit

**Comment by atuleu** [comment]
Scroller jump back to previous time after scrolling

**Comment by atuleu** [comment]
Current version works fine under macbook pro retina 15" late 2013 on Mint Tina running gnome 3 on Xorg and Qt 5.6

Do not work on Ubuntu 20.04 on a ryzen 7 custom build, Gnome 3 on Wayland and Qt 5.13

Maybe related to window manager, Xsever or Qt 5.13 ?
