### ISSUE TITLE
Adds Windows and macOS support

### ISSUE THREAD

**Issue by atuleu** [formicidae-tracker/studio#12]
Maybe it will not be supported, but at least try in the long term

**Comment by atuleu** [comment]
After fiddling on this a few hours.

Building on windows is not easy. Even if now tools like [vcpkg](https://github.com/microsoft/vcpkg) helps the installation of dependencies, and Visual Studio as a free to use Community Edition, the setup for protobuf is not easy, and there will be some work needed to port it on this non unix platform.

As for OS X, it should be much more easier, and I tried to setup a docker cross compilation environment to test the current codebase against MacOS. But due to lot of runtime dependecy of the project, it is not easy to setup this environment as we need to recompile a lot of things and automated tools like homebre aren't design for cross-compilation setup AFAIK.

I would like to close this issue and target only a Linux development and distribution.

**Comment by tomrichardson** [comment]
Linux is fine for me.

**Comment by tomrichardson** [comment]
Windows 3.14?

**Comment by atuleu** [comment]
I would more gladly target DOS at that point. At least it has a decent user interface. But orienting ant in ascii art won't be easy.
