### ISSUE TITLE
FortMyrmidon R bindings: some hyperlinks broken in the help

### ISSUE THREAD

**Issue by nathaliestroeymeyt** [formicidae-tracker/studio#131]
When trying to access fmMatcher or fmMatcherAny by clicking on the hyperlink from the help for fmQueryComputeAntTrajectories or fmQueryComputeAntInteractions, the links to not lead anywhere but produce the message:

_No help found for topic fmMatcher-class in any package._

or

_No help found for topic fmMatcherAny() in any package_

Links work fine from main help menu

**Comment by atuleu** [comment]
Fixed in 0.6.0
