### ISSUE TITLE
AntID format in R bindings

### ISSUE THREAD

**Issue by nathaliestroeymeyt** [formicidae-tracker/studio#133]
In the R bindings I would like to always stick to the hexadecimal format when outputing antID. Otherwise people are going to get confused between antID (decimal, in R) - tagID (decimal, in fort studio) and antID (hexadecimal, in fort-studio).

I know there is a constraint for there not to be a direct correspondance between TagID and AntID for optimisation reason, but in that case it would be much better for AnID to always be referred to as hexadecimal so people don't get confused (and also to more easily match the antID displayed in R with those displayed in the visualiser in fort-studio)

**Comment by atuleu** [comment]
I think it may be better to go for a full 360 on this matter.

We should output antID as decimal in fort studio, tagID as hexadecimal. More confusing for tags but the purpose is to exactly enforce user forget about them, they are just identification details in your study. And we use decimal for ant tag display

**Comment by nathaliestroeymeyt** [comment]
Yes I agree, that's a better plan

**Comment by atuleu** [comment]
Done in v0.5.0
