### ISSUE TITLE
Question: correspondance TagID / AntID

### ISSUE THREAD

**Issue by nathaliestroeymeyt** [formicidae-tracker/studio#134]
In R, is there a function that outputs a table of correspondence between TagID and AntID? Just in case two users oriented their ants independently and want to compare their analyses?

**Comment by atuleu** [comment]
No, but you could easily build that table from the API: 
```R
ants <- e$cAnts()
for ( i in seq(1,ants) ) {
  a <- ants[[i]]
  # a$antID() gets the antID
  identifications <- a$identifications()
  for ( i in seq(1,length(identifications)) {
    i$tagValue() # gets the tag ID
  }
}
```

Then its is up to you to build the structure you want with this information. Please note that an Ant ID could have N identification with sometimes the same tagID, sometime not.
