### ISSUE TITLE
Querying directional interactions with fmMatcher

### ISSUE THREAD

**Issue by nathaliestroeymeyt** [formicidae-tracker/studio#135]
In our applications, we are often interested in directional interactions, e.g. pathogen-exposed workerd being groomed by other workers, or a "super-carer" grooming other workers.

In the first example we would want to query interactions involving any capsule in our ant of interest with a specific capsule (e.g. head) in any other ant.
In the first example we would want to query interactions involving a specific capsule in our ant of interest (e.g. head) with any capsule in any other ant.

Based on our slack discussion last night I do not think these two particular scenarios can be queried using fmMatcher statements - but it would be quite important for us, and it would be useful to have it soon as we attempt to automatically detect the behaviours annotated by Adriano during the lockdown.

**Comment by atuleu** [comment]
The second example is missing.

An existant query for that frst example would be : 
```R
idMatcher <-fmMatcherAntID(superCarrierID)
typesMatchers <- list ( fmMatcherInteractionType(1,interestID),
                        fmMatcherInteractionType(2,interestID)) # add for every shapetTypeID in the experiment
fmMatcherAnd(list(idMatcher,fmMatcherOr(typesMatchers)))
```

with a bit of knowledge, you should even be able to construct the typesMatcher list from the experiment by querying the types in the experiment.

Before introducing new functionnality to the API, let see if the current state fills your purpose.

**Comment by nathaliestroeymeyt** [comment]
Thanks - great to hear that the first option can already be implemented! 

I think I need to get my head around how this fmMatcher works. I guess all the existing documentation can be accessed online by clicking on the C++ wrappers within the R help?

**Comment by atuleu** [comment]
You could maybe try to read directly the doc here: https://formicidae-tracker.github.io/studio
