### ISSUE TITLE
Question: can we access tag squareness from R bindings?

### ISSUE THREAD

**Issue by nathaliestroeymeyt** [formicidae-tracker/studio#137]
When the ants self-groom, they often "shift" sideways so much that their tag squareness decreases a lot. For our automatic behaviour dectection, that would actually be a very useful cue: busy ants will often have many changes of tag squareness as they tilt their body while performing their task (e.g. self-grooming, allogrooming, trophallaxis), whereas their tag squareness will remain constant when they are resting. Could tag squareness be added as an output alongside with X, Y, Angle and Zone in the trajectory query?

**Comment by atuleu** [comment]
This is not possible. The tag squareness depends on the coordinate of each detected tag corner. Those are not saved by artemis as they will multiply by five the amount of data to save.
