### ISSUE TITLE
Glitch in colour definition - Visualisation tab

### ISSUE THREAD

**Issue by nathaliestroeymeyt** [formicidae-tracker/studio#169]
Strange behaviour: when you select a few ants and define a new colour for the first time, it works fine. But when just after that, you select different ants and want to give them the same colour, it does not work (you can click on the colour you want but that does not change anything in the display). Instead you need to first give them a different colour, exit the colour selector, then reopen the colour selector and choose the colour you wanted,

I'm happy to show you the behaviour on a screen share if that's not very clear

**Comment by atuleu** [comment]
With new refactoring this seems to be fixed, however proper unit testing is not yet implemented.
