### ISSUE TITLE
Zone defined but size remains 0 and zone is not "recorded"

### ISSUE THREAD

**Issue by nathaliestroeymeyt** [formicidae-tracker/studio#170]
I'm not too sure what I'm doing wrong, but I had to try about 10 times to get it right today and I'm not sure what made it work in the end... 
Basically, when I want to define a new zone: I first add a new zone within the space, then I rename that zone, and then I select the correct zone name in the scroll down menu and then choose polygon to define the zone. But most of the time, even though the zone appears (coloured polygon overlaid over the image), the "size" attribute remains at 0 and the zone is not remembered when zaving the file.
No idea if it's a reproducible bug or if it's me doing something wrong. Perhaps we can also have a screen share so I show you what I'm doing and you can point out what's wrong?

**Comment by atuleu** [comment]
I think you never leave the polygon addition mode, and therefore the polygon is not yet added.

When creating a polygon, you add points by clicking on the frame. Clicking always add new vertices, until : 
* You right click to close the polygon
* You close the polygon by adding a vertice on top of the first vertice
