### ISSUE TITLE
Frames are identified by frame number in the zoning tab

### ISSUE THREAD

**Issue by nathaliestroeymeyt** [formicidae-tracker/studio#171]
Since everywhere else frames are identified by their time rather than the frame number - and since you told me we should forget about frame number anyway - can we switch to display the time rather then the frame number in the zoning tab?

**Comment by atuleu** [comment]
They are actually identified by their URI in the myrmidon file. A notion that I was relying a lot, but now is more internal.
The view will be unified in looks and feel with the new identification window
