### ISSUE TITLE
Add detection rate per tag

### ISSUE THREAD

**Issue by AdrianoWanderlingh** [formicidae-tracker/studio#69]

**Comment by atuleu** [comment]
Okay, you need to be more specific

**Comment by atuleu** [comment]
@AdrianoWanderlingh please be a bit more specific for this request.

**Comment by AdrianoWanderlingh** [comment]
When inspecting the quality of tracking data, knowing beforehand the proportion of detections over the full lenght of the video is very useful to determine if tracking/behavioural data should be dropped or not. This could be introduced in a collapsible column like "ant selector" or somewhere else such that doesn't occupy permanently space in the screen.

**Comment by atuleu** [comment]
Notes:
* Number of Frame detected
* Number of Frame with multiple detection
* First Timestamp
* Last Timestamp
* Trajectory Gap histogram
