### ISSUE TITLE
Adds Video frame navigation

### ISSUE THREAD

**Issue by atuleu** [formicidae-tracker/studio#71]
* Frame-By-Frame scrolling when paused
* Jump by 10 seconds

**Comment by atuleu** [comment]
@AdrianoWanderlingh , proposed shortcuts:
* J/L : skip 10 seconds forward / backward
* Shift+J / Shift + L : skip 1 minute forward / backward
* Ctrl+J / Ctrl + L : skip 10 minute forward / backward

+/- 10 second bound to the clickable button

**Comment by AdrianoWanderlingh** [comment]
I think they are good!
