### ISSUE TITLE
Error opening raw tracking files

### ISSUE THREAD

**Issue by tomrichardson** [formicidae-tracker/studio#83]
After copying data from current tracking experiment stored here: /scratch/axiom/FAC/FBM/DEE/lkeller/tracking_sys/tkay

.. I load the 'Nee_Col1_MD_Nest.0000' folder by clicking the  '+' in the 'Spaces and directories' tab on screen #1.... Which works, sortof; the directory appears as a space, but no other files are visible - see attached.

![No_videos_loaded](https://user-images.githubusercontent.com/1412908/83016599-20e9ab80-a01a-11ea-8de9-9aa282bd574d.png)

 No videos are visible in the 'visualise' tab either:

![No_videos_loaded_in_visualise_tab](https://user-images.githubusercontent.com/1412908/83016842-876ec980-a01a-11ea-8101-0d683d7d3ae5.png)

Running Linux Mint 19.1

**Comment by atuleu** [comment]
Could you try to make a new experiment file and relaod the tracking data directory, but this time in /media/tom/HDD/HoneyBee/

As explained in the [fort::myrmidon:Experiment class documentation](https://formicidae-tracker.github.io/studio/docs/latest/api/#fort::myrmidon::Experiment/fort::myrmidon::Experiment), when you move file arround, you have to keep the same relative structure with the myrmidon files and the tracking data directory. As the myrmidon file keeps a relative link to the tracking data directory, these links mayl become broken if you move a single thing arround (you can move all files, but not just one of the file)

**Comment by tomrichardson** [comment]
'relaod the tracking data directory' could mean several things..

I assume that you have checked on the tracking room computers and found that the original folder containing the nest & foraging folders was 'HoneyBee', and that I should rename the folder 'Honeybee_tracking_microbiota' -> 'HoneyBee'...? 

I have just done this, and Fortstudio has frozen.

**Comment by atuleu** [comment]
Ok I think it would be better if we use slack for this kind of support... You are not giving the full context of the error, and this is not yet a bug

Please go here : https://formicidae-tracker.slack.com/archives/C014BQQ19MG
