### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by tomrichardson** [formicidae-tracker/studio#84]
There is a rather useful feature that would be nice to have, particularly for large datasets; a function to infer the orientation of the tag on the ant.

I did this in R in the following manner:

- for each trajectory fix, compare the tag heading with the movement heading (which you get by drawing a line between the previous & the current position).

- For each trajectory fix, calculate the difference between the tag heading and the movement heading. Thus, a tag that has been glued with the front of the tag perfectly aligned with the body orientation will have difference = 0. When the tag is rotated anticlockwise with respect to the head-tail axis of the individual, the difference will be in the range 1 to 180 degrees, and when the rag is rotated clockwise, the difference will be in the range -1 to -180.

- Repeat this over all points in a given individuals trajectory, to produce a distribution of differences.

- Because moving animals tend to move in the direction that they are facing (i.e. forwards), you can use the distribution of differences to infer the orientation of the tag, and hence the  correction that needs to be applied. Specifically, you can look for a peak in the distribution (see histogram pdf - each hist is a different ant). The first peak represents trajectory segments when the ant was moving forward, and the second peak (which is always 180 degrees from the first) represents times when the ant was moving backwards.

[Automatic_Tag_Orientation.pdf](https://github.com/formicidae-tracker/studio/files/4688519/Automatic_Tag_Orientation.pdf)

If you look at the pdfs, the tags of ants 534, 537, 541, 547 & 549 happened to have been glued onto the thorax in exactly the correct direction, whereas those of the others were glued on with rotations of +/- ~90 degrees..

As the forwards-tendency is exaggerated at high speeds, I thresholded the distribution by excluding all occasions when the ant was moving slowly (in the hists, the thresholding is indicated by the greyscale  - white = no speed threshold, dark grey = high speed threshold).

Hope this is clear...? I have R scripts to do this, but it's all embarrassingly inelegant.

Also, because ants are hard-core & individuals bounce off one another, it would also be possible to infer the body dimensions / outline of a given individual just by looking at the spatial distribution of the positions of other tags around a given tag; if we were to plot a map of the positions of other tags around each tag, we'll see an elliptical 'silhouette' defining the edges of the body...

I realise this is much more than what was envisaged when starting out, but I'd be interested to hear whether you think it's feasible in FORT studio.

[Automatic_orientation_correlation.pdf](https://github.com/formicidae-tracker/studio/files/4688518/Automatic_orientation_correlation.pdf)

**Comment by atuleu** [comment]
Hi,

I believe these kind of feature are just too much complex for the purpose of the myrmidon API.
