### ISSUE TITLE
List of features to change/modify.

### ISSUE THREAD

**Issue by tomrichardson** [formicidae-tracker/studio#91]
- 'Show collisions' works, but it's unclear how the collisions are defined; the collision definition should be transparent & adjustable (e.g. only head-to-head collisions, only head-to-tail collisions, etc etc).
- Currently  each individual that has been oriented & had its body polygon defined appears in 'Visualize' as two orange circles, one large, one small, with the smaller at the head. Wouldn't it be better to overlay the actual oriented polygons..?
- 'Show IDs' option in visualize tab shows the hex ids - the actual tag number should be displayed.
- 'Zoom on ant' does not appear to be functional

**Comment by atuleu** [comment]
> * 'Show collisions' works, but it's unclear how the collisions are defined; the collision definition should be transparent & adjustable (e.g. only head-to-head collisions, only head-to-tail collisions, etc etc).
Quite complicated to implement. Show Collision is simple and straight forward: it shows when any collisions are detected. The aim to fort studio visualization is to quickly understand what happening, not to actually analyze data. The API is there for that purpose. If you need to display something more complicated for example as an illustration for a publication, then you should compute interaction you want to show, and use OpenCV to create a new movie file.
> * Currently  each individual that has been oriented & had its body polygon defined appears in 'Visualize' as two orange circles, one large, one small, with the smaller at the head. Wouldn't it be better to overlay the actual oriented polygons..?
Could be very slow to display, therefore something simpler is displayed. Could be considered optional
> * 'Show IDs' option in visualize tab shows the hex ids - the actual tag number should be displayed.
I strongly disagree with this. The purpose of myrmidon is to actually forget the TagID. Only statistics are displayed to help prune bad tag and not identify individuals tagged with those tag value. Get used to use AntID, as it is the only thing you can use to refer anything in the myrmidon API. There are absolutely no relation between AntID and Tag number. Just forget about tag number. It is discutable if AntID should be reported as decimal and TagId as hexadecimal. But just only work with AntID from now on. 
> * 'Zoom on ant' does not appear to be functional
You must select an Ant first in the selector. Then you can zoom.
